---
- hosts: local
  roles:
    - { role: browsers, tags: browsers }
    - { role: slack, tags: slack }
    - { role: discord, tags: discord }
    - { role: vscode, tags: vscode }
    - { role: neovim, tags: neovim }
    - { role: gitify, tags: gitify }
    - { role: spotify, tags: spotify }
