---
- hosts: local
  roles:
    - { role: fonts, tags: fonts }
    - { role: sound, tags: sound }
    - { role: bluetooth, tags: bluetooth }
    - { role: discord, tags: discord }
    - { role: slack, tags: slack }
    - { role: vscode, tags: vscode }
