---
- hosts: local
  roles:
    - { role: fonts, tags: fonts }
    - { role: sound, tags: sound }
    - { role: bluetooth, tags: bluetooth }
    - { role: discord, tags: discord }
    - { role: slack, tags: slack }
    - { role: vscode, tags: vscode }
    - { role: browsers, tags: browsers }
    - { role: dotfiles, tags: dotfiles }
    - { role: fcitx, tags: fcitx }
    - { role: eww, tags: eww }
    - { role: rofi, tags: rofi }
    - { role: polybar, tags: polybar }
